### ISSUE TITLE
Using sweep with 2 stages

### ISSUE THREAD

**Issue by shakedpe** [hlzhang109/DDG#12]
Hi,
Thanks for you code!
I wanted to recreate results and run the sweep code, however you algorithm consists of 2 stage training (stage==0/1) and im not clear on how you run the sweep in this scenario. I looked in your sweep code and it is a copy of the one from DomainBed, no updates to the 2 stage training you use. Can you please share the code of the sweep?
Thanks

**Comment by hlzhang109** [comment]
We didn't use sweep for our model. A feasible way is to first train the GAN and use sweep the code for the second stage.
