### ISSUE TITLE
reproduce the model in rotated-mnist

### ISSUE THREAD

**Issue by rookiehb** [hlzhang109/DDG#13]
Hi, could I ask for some details about reproducing the model in Rotated-MNIST?

I follow the instructions you provided, but I can't get the impressive disentangled effect just like the images in the appendix :(

**Comment by hlzhang109** [comment]
Hi, could you please provide more details about your settings like the code and results?

**Comment by rookiehb** [comment]
I train the DDG model in the RotatedMNIST dataset without modifying any code or hyperparameter. 

And I visualize some images in function called algorithm.update() in train.py line 243, including variables called images_a, images_b, x_ab, x_ba

But most digits in x_ab(or x_ba) don't have the style of digits in images_b(images_a)

images_a, x_ab, images_b, x_ba are as follows accordingly
images_a
![a](https://user-images.githubusercontent.com/98326664/209816896-1cd61cbf-f5d4-4756-9ec1-469d1bd3291f.png)
x_ab
![ab](https://user-images.githubusercontent.com/98326664/209817229-9f9d01f7-acfd-43ae-890a-2d2fdb7474c5.png)
 images_b
![b](https://user-images.githubusercontent.com/98326664/209817244-8c973e63-b92c-40d2-a8ee-dd50b4f98c1a.png)
x_ba
![ba](https://user-images.githubusercontent.com/98326664/209817254-fb928437-c514-4999-847a-2b4ace808e1b.png)

**Comment by yfzhang114** [comment]
The default parameter for RotatedMNIST in hparams_registry.py is stage 1, not stage 0. Please set it to stage 0 for style disentanglement.
![image](https://user-images.githubusercontent.com/53161950/210077803-f316fe1e-9114-4d7c-890f-cf669bdfbddd.png)

We make the following change such that you can modify the stage parameter for RotatedMNIST from the argument in train.py.

![image](https://user-images.githubusercontent.com/53161950/210077975-2f5dc6c4-dc42-4cd0-90b5-15eb47806653.png)
