### ISSUE TITLE
No module named 'scripts.write_2images'

### ISSUE THREAD

**Issue by Lu-Tan** [hlzhang109/DDG#3]
Thank you for the amazing work!

Could you please upload the file 'write_2images.py' in the scripts folder? When I try to train the decoder, this module is imported in algorithm.py but I couldn't find it.

**Comment by hlzhang109** [comment]
Thanks! please find https://github.com/hlzhang109/DDG/blob/78e045e6542cf4cddf2e0958e663456e76c639d0/scripts/save_images.py#L24
