### ISSUE TITLE
GAN training - x_ab and x_ba errors

### ISSUE THREAD

**Issue by franciscocms** [hlzhang109/DDG#6]
Hi! First, congratulations on this work, it's very interesting!
I've been trying to reproduce your results (only with RotatedMNIST dataset), but then something strange happened: the pre-trained gan model that results from stage 0 generates _x_ab_ and _x_ba_ images wrongly, they do not present the content and style parts from the correspondent input image and end up being an image that is almost a reconstruction of the style image - a or b accordingly)... then in stage 1, these generated images continue to be retrieved with this pre-trained model as it shows in _algorithms.py_ line 1055, so class predictions for these images will always be wrong over stage 1 training. Was this supposed to happen or did I make something wrong that you can easily identify? 
Thank you very much.

**Comment by hlzhang109** [comment]
Hi, thanks! We reran the code and didn't find anything wrong about the process.
