### ISSUE TITLE
why you change the backbone

### ISSUE THREAD

**Issue by hackmebroo** [hlzhang109/DDG#8]
![1](https://user-images.githubusercontent.com/43629556/185068809-9b8dcf7d-829f-4c0b-a422-a94d45edc781.png)
I have a question, why you remove the bn layer from resnet, the removal of bn may severely influence the result, do you make fair comparison in your paper

**Comment by hlzhang109** [comment]
It is an original function from DomainBed which we didn't use for our experiments 
https://github.com/facebookresearch/DomainBed/blob/4c16e322bd1a5b339b908f43ae3440341c512e90/domainbed/networks.py#L12
