### ISSUE TITLE
How does this code test the trained model?

### ISSUE THREAD

**Issue by NingMa-AI** [hlzhang109/DDG#9]
Hello, thanks for your excellent work. I find this repo only contains training commands. I can not determine how to select and test the trained model on the target domain.
I find that there is a folder called "test", do you have any reletaed commands?

**Comment by yfzhang114** [comment]
This code is used for the sweep command, in this paper, we use test-domain validation, where we choose the model maximizing the accuracy on a validation set that follows the same distribution of the test domain. The test folder is not used.
